# -*- coding: utf-8 -*-
"""Anomaly_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jDWTMfoTiIOdfwUEAvpuLwBfFVoVABQq
"""

!pip install pycaret

#Import dataset
from pycaret.datasets import get_data
anomaly = get_data('anomaly')
from pycaret.anomaly import *
exp_anomaly = setup(anomaly)

anomaly

iforest = create_model('iforest')
 plot_model(iforest)

knn = create_model('knn')
plot_model(knn)

knn_predictions = predict_model(knn, anomaly)

knn_predictions

